# Generated by Django 5.2.8 on 2025-11-17 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Salas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('sigla', models.TextField(max_length=10)),
                ('campus', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('ano', models.IntegerField()),
                ('finalizada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='meuapp.sala')),
            ],
            options={
                'verbose_name_plural': 'Conferências',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Patrimônio')),
                ('descricao', models.TextField(max_length=1000)),
                ('tipo', models.CharField(choices=[('mobiliario', 'Mobiliário'), ('eletrodomestico', 'Eletrodoméstico'), ('informatica', 'Informática'), ('escritorio', 'Escritório'), ('outros', 'Outros')], max_length=20)),
                ('status', models.CharField(choices=[('bom', 'Bom'), ('danificado', 'Danificado'), ('inutilizado', 'Inutilizado')], default='bom', max_length=20)),
                ('valor_aquisicao', models.FloatField(blank=True, null=True)),
                ('valor_depreciado', models.FloatField(blank=True, null=True)),
                ('numero_serie', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('sala_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios', to='meuapp.sala')),
            ],
            options={
                'verbose_name_plural': 'Inventários',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='meuapp.setor'),
        ),
        migrations.CreateModel(
            name='ItemConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_conferido', models.CharField(choices=[('bom', 'Bom'), ('danificado', 'Danificado'), ('inutilizado', 'Inutilizado')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('imagem_observacao', models.ImageField(blank=True, null=True, upload_to='observacoes/')),
                ('data_conferencia', models.DateTimeField(auto_now_add=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='meuapp.conferencia')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.inventario')),
            ],
            options={
                'verbose_name_plural': 'Itens de Conferência',
                'unique_together': {('conferencia', 'inventario')},
            },
        ),
    ]
